
target-y := event_test
event_test-source-y := event_test.c
event_test-include-y := ../src 
event_test-library-path-y := ../build/src
event_test-library-y := -levent_poll
install-y := event_test:bin/

include ../Build.mk
