
library-y := libevent_poll.so
libevent_poll.so-source-y := event.c 
libevent_poll.so-header-y := event_poll.h
install-y := libevent_poll.so:lib/
install-y += event_poll.h:include/

include ../Build.mk

